### ISSUE TITLE
feature request- add percent sequence identity to output aggregated features file

### ISSUE THREAD

**Issue by ecpierce** [Arcadia-Science/ProteinCartography#30]
Hi!

It would be great if you could add a column for percent sequence identity for each comparison to the final output table. We think it could be really useful to compare % sequence id directly to tm-score, but currently it isn't easy to access this info. If this information already exists, adding it to the output would be helpful!

Best, 
Emily

**Comment by braebigge** [comment]
This was addressed in [PR 39](https://github.com/Arcadia-Science/ProteinCartography/pull/39), will make a new issue for calculating all-v-all seq similarity.
