### ISSUE TITLE
.faa files fail in search mode

### ISSUE THREAD

**Issue by borgesadair1** [Arcadia-Science/ProteinCartography#62]
I was trying to run search mode on some protein fasta files with a .faa file extension and the job failed for what appears to be a lack of BLAST hits. 

`usage: aggregate_lists.py [-h] -i INPUT [INPUT ...] -o OUTPUT
aggregate_lists.py: error: argument -i/--input: expected at least one argument` 

This error resolved when I changed the file extension to .fasta 
Would it be possible to adjust the code such that it can recognize .faa file extension as well as .fasta file extensions?

**Comment by mezarque** [comment]
Addressed by 4453ed3022108a60791c3829777db947691f3182

**Comment by mezarque** [comment]
Probably we should handle this in a more elegant way than using the file suffix in the future, maybe [SeqIO](https://biopython.org/wiki/SeqIO)?

**Comment by mezarque** [comment]
The original error should be resolved as of the [most recent release](https://github.com/Arcadia-Science/ProteinCartography/releases/tag/v0.4.2).
