### ISSUE TITLE
Multiple key proteins fails at plot_interactive.py

### ISSUE THREAD

**Issue by braebigge** [Arcadia-Science/ProteinCartography#64]
When using the pipeline with multiple key proteins, the pipeline fails during the plot_interactive.py. I think this is because when parsing the command line arguments, "-k", "--keyids" is set to `nargs="?"` which makes the argument optional but allows for only one argument. I think that `nargs="*"` would allow for multiple optional arguments. (This is line 158 in plot_interactive.py). 

I tried this replacement in my own run. The plotting worked and all of my key proteins were highlighted properly. I also tested this on a small run without a key file, and it worked fine.

**Comment by mezarque** [comment]
should be fixed by 262ac83010627fc5ec1f6d120f891c57e68b34e6
