### ISSUE TITLE
snakemake errors running demo

### ISSUE THREAD

**Issue by kylekimler** [Arcadia-Science/ProteinCartography#66]
Hi ProteinCartography team, 

I'm on an M2 mac running into some issues trying the snakemake demo. I have the conda environment all set up and activated. When I run the snakemake command:

`snakemake --snakefile Snakefile --configfile demo/config_actin.yml --use-conda --cores 6`

I receive:
`CreateCondaEnvironmentException:
Could not create conda environment from /Users/kylekimler/Projects/.../ProteinCartography/envs/run_blast.yml:
Command:
mamba env create --quiet --file "/Users/kylekimler/Projects/.../ProteinCartography/.snakemake/conda/b1b83db7a7ba8aea84a0e931f8dfe832_.yaml" --prefix "/Users/kylekimler/Projects/.../ProteinCartography/.snakemake/conda/b1b83db7a7ba8aea84a0e931f8dfe832_"
Output:
Could not solve for environment specs
The following package could not be installed
└─ blast 2.14.0**  does not exist (perhaps a typo or a missing channel).`

I've tried installing foldseek and blast separately and adding to $PATH but it did nothing to help. Any suggestions?

**Comment by mezarque** [comment]
Hey Kyle, thanks for reaching out! We've had similar issues caused by conflicts between different versions of `conda` that work on different processors (Apple vs. Intel silicon).

Could you share the text that prints when you run `conda info` from your command line interface (e.g. Terminal)?

**Comment by jshanahan1** [comment]
Hello, I have a similar issue with the demo not being able to install Foldseek. I am using a 2021 MacBook Pro 14in M1 Pro.  Here is the output from running "conda info":

 active environment : cartography_tidy
    active env location : /Users/jackshanahan/miniconda3/envs/cartography_tidy
            shell level : 2
       user config file : /Users/jackshanahan/.condarc
 populated config files : 
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.5=0
                          __unix=0=0
       base environment : /Users/jackshanahan/miniconda3  (writable)
      conda av data dir : /Users/jackshanahan/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jackshanahan/miniconda3/pkgs
                          /Users/jackshanahan/.conda/pkgs
       envs directories : /Users/jackshanahan/miniconda3/envs
                          /Users/jackshanahan/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.7.4 requests/2.29.0 CPython/3.11.4 Darwin/22.6.0 OSX/13.5
                UID:GID : 504:20
             netrc file : None
           offline mode : False

**Comment by kylekimler** [comment]
Hi Dennis, thanks, here's mine as well

active environment : cartography_tidy
active env location : /Users/kylekimler/miniconda3/envs/cartography_tidy
shell level : 2
user config file : /Users/kylekimler/.condarc
populated config files : 
conda version : 23.5.2
conda-build version : not installed
python version : 3.11.4.final.0
virtual packages : __archspec=1=arm64
              __osx=13.4=0
              __unix=0=0
base environment : /Users/kylekimler/miniconda3  (writable)
conda av data dir : /Users/kylekimler/miniconda3/etc/conda
conda av metadata url : None
channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
              https://repo.anaconda.com/pkgs/main/noarch
              https://repo.anaconda.com/pkgs/r/osx-arm64
              https://repo.anaconda.com/pkgs/r/noarch
package cache : /Users/kylekimler/miniconda3/pkgs
              /Users/kylekimler/.conda/pkgs
envs directories : /Users/kylekimler/miniconda3/envs
              /Users/kylekimler/.conda/envs
    platform : osx-arm64
  user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Darwin/22.5.0 OSX/13.4
    UID:GID : 501:20
  netrc file : None
offline mode : False

**Comment by mezarque** [comment]
Thanks for sending over this info!

Based on other similar issues we've had, I think this issue is caused by installing the macOS Apple M1 64-bit version of conda. It should be resolved by instead installing the macOS Intel x86 64-bit version of conda (see [this page](https://docs.conda.io/projects/miniconda/en/latest/)). I think the error is thrown because bioconda (which contains blast) [doesn't yet support osx-arm64 architecture](https://github.com/conda/conda/issues/11216). 

Even if you are running an M1 machine, you should be able to run the Intel x86 64-bit version of conda thanks to [Rosetta](https://support.apple.com/en-us/HT211861), which should already be installed on your machine. You may have to open your Terminal or other CLI app using Rosetta, as described in the link above.

Let me know if this solves the issue; we can update our README to include more precise instructions for installing `conda`.

**Comment by kylekimler** [comment]
This method works great! Thank you! And thanks for teaching me about Rosetta
