### ISSUE TITLE
consider adding resource execution settings to `config.yml`

### ISSUE THREAD

**Issue by taylorreiter** [Arcadia-Science/ProteinCartography#70]
introduced in the test data set in #69. I believe this should not create any problems for the standard use case where this pipeline is executed on someones personal computer, but it would be good to confirm this before adding it to `config.yml` as well.

```
resources: 
    mem_mb: 16 * 1000
cores: 8
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 10
```

**Comment by mezarque** [comment]
These defaults have been added to `config.yml` as of the [most recent release](https://github.com/Arcadia-Science/ProteinCartography/releases/tag/v0.4.2).
