### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ValWood** [Arcadia-Science/ProteinCartography#71]
Hi,

I was reading https://research.arcadiascience.com/pub/resource-protein-cartography/release/5

I have a question. How do you know that most of your "outliers" aren't incorrect gene structure predictions? This seems the most likely explanation. There are up to 50% gene structure errors in genomes that have not had the gene structures manually reviewed.

See for example PMID: 31787936

**Comment by mezarque** [comment]
Hi Val, thanks for pointing this out! This is an important consideration. We don't have a quick way of knowing whether gene structure prediction errors are responsible for outlier proteins in our analyses. We rely on retrieving protein sequences from UniProt, some of which may be derived from transcriptomic data, while others might be derived from predicted gene models. For individual proteins, we can't guarantee that the sequences are correct.

However, given that our analyses are focused primarily on clusters of proteins that originate from different organisms, I would be surprised if outlier clusters were completely driven by gene structure prediction error. I would not expect gene structure predictions to fail in a way that generates similarly unusual proteins across different genomes from different organisms, which may have been generated by different groups of researchers and using different methods. 

Ultimately, our tool is focused on providing users the ability to rapidly explore proteins similar to their proteins of interest. Downstream analyses, such as validation of protein sequence, would still be necessary for definitively assigning protein function.

**Comment by ValWood** [comment]
OK, that would be unlikely if they are clusters of outliers!
v
