### ISSUE TITLE
Long protein names cut off info in hovertext box

### ISSUE THREAD

**Issue by scienceYeeSu** [Arcadia-Science/ProteinCartography#74]
I've noticed that proteins with super long names mess up how the pop up box is displayed in the interactive plots, which cuts off most of the useful information. I've tried shrinking and expanding my window, as well as zooming in and out of the plot itself, but none of those have fixed it.
![image](https://github.com/Arcadia-Science/ProteinCartography/assets/124650729/e6cf9cab-38de-49f1-806f-c47d949a0b05)

**Comment by mezarque** [comment]
Thanks for letting us know about this issue! We're considering solutions to this and will let you know if this is resolved by a future release.

**Comment by mezarque** [comment]
Our [most recent release](https://github.com/Arcadia-Science/ProteinCartography/releases/tag/v0.4.2) should address this issue. Let us know if you have any questions!
