### ISSUE TITLE
ESMFold API for structure prediction is broken - won't work with SSL certificate checks

### ISSUE THREAD

**Issue by naailkhan28** [Arcadia-Science/ProteinCartography#80]
### Description of the bug

Since the FAIR proteins team left Meta, the SSL certificates for the ESM Atlas domain name have been broken. This results in API services throwing SSL errors if you try to access them programatically. See this issue in from the ESM repo for more info:

https://github.com/facebookresearch/esm/discussions/627

A quick fix I've found in my own scripts to get around this is to disable SSL checks in Python using the `ssl` module. I have a PR I can submit for this if you'd like :)

**Comment by mezarque** [comment]
Thanks so much for letting us know about this! If you'd be willing to open a PR that would be much appreciated.
