### ISSUE TITLE
Missing file in `setup.py`

### ISSUE THREAD

**Issue by alexj-lee** [Arcadia-Science/ProteinCartography#87]
### Description of the bug

In `setup.py` the following file:

`ProteinCartography/extract_input_protein_distances.py`

is listed under `scripts` but is seemingly not in the repo anymore. When I attempted to pip install this package, there was an error. Not sure if it just on my machine, but I tested it on my laptop and on a local server and as far as I can tell this file has been removed? I don't think this is necessary to run the default `snakemake` workflow but is an issue for those who want to pip install the package (for example in a Docker image). Apologies if my assessment is incorrect! Thanks a lot for putting this out.  

### Command used and terminal output

```console
pip install git+https://github.com/Arcadia-Science/ProteinCartography/

(same result with cloning and building via `pip install .`
```

**Comment by mezarque** [comment]
Hi there, thanks for trying out ProteinCartography! This tool is not actually a package – it's a collection of scripts meant to be run using the included Snakemake pipeline. Therefore, it's not currently designed to be `pip` installable (the inclusion of `setup.py` is an artifact from an earlier stage of the pipeline's development and should be removed).

Please follow the instructions in the [Quickstart](https://github.com/Arcadia-Science/ProteinCartography?tab=readme-ov-file#quickstart) section to set things up.

If you'd like to run this within a Docker image, I'd recommend cloning the repo and then copying the source code into the image. I haven't tried this myself, but I think it should work.

**Comment by alexj-lee** [comment]
Yes I understand. I didn't realize what your intent was with the package. Thanks for your comment.
